name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add execute permission
        run: chmod +x ./gradlew

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

      - name: Artifact version
        id: tag_reformat
        run: echo "::set-output name=artifact-version::$(cut -d'v' -f2- <<< '$cut -d'/' -f3- <<< '${{ github.ref }}'' | tr '[:lower:]' '[:upper:]')"

      - name: Build
        run: ./gradlew build -Pversion=${{ steps.tag_reformat.outputs.artifact-version }}

      - name: Get Binary name
        id: get_binary_name
        run: |
          file_name="$(ls ./build/libs/*-${{ steps.tag_reformat.outputs.artifact-version }}.jar | head -1 | cut -d'/' -f4-)"
          echo "::set-output name=binary_name::$file_name"
          echo "::set-output name=reformatted_name::$(tr ' ' '-' <<< $file_name)"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/${{ steps.get_binary_name.outputs.binary_name }}
          asset_name: ${{ steps.get_binary_name.outputs.reformatted_name }}
          asset_content_type: application/jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.get_binary_name.outputs.reformatted_name }}
          path: ./build/libs/${{ steps.get_binary_name.outputs.binary_name }}